// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAnqC8TJcrK5bijM2JCRpmhszyYIgx5DA',
    appId: '1:388888154670:web:32069c9b95d15d1dde05bf',
    messagingSenderId: '388888154670',
    projectId: 'loginsignup-87c6b',
    authDomain: 'loginsignup-87c6b.firebaseapp.com',
    storageBucket: 'loginsignup-87c6b.appspot.com',
    measurementId: 'G-CQEJN3WZ7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4ba9DOfHrcpsFxwFWghkrZ3MImu1FeGE',
    appId: '1:388888154670:android:48bd2b57bca8c431de05bf',
    messagingSenderId: '388888154670',
    projectId: 'loginsignup-87c6b',
    storageBucket: 'loginsignup-87c6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALr3YKv3M2v2LHk1GAy0fjnibkhKf1tVo',
    appId: '1:388888154670:ios:aabaadd5ac591c81de05bf',
    messagingSenderId: '388888154670',
    projectId: 'loginsignup-87c6b',
    storageBucket: 'loginsignup-87c6b.appspot.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALr3YKv3M2v2LHk1GAy0fjnibkhKf1tVo',
    appId: '1:388888154670:ios:aabaadd5ac591c81de05bf',
    messagingSenderId: '388888154670',
    projectId: 'loginsignup-87c6b',
    storageBucket: 'loginsignup-87c6b.appspot.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAnqC8TJcrK5bijM2JCRpmhszyYIgx5DA',
    appId: '1:388888154670:web:2bf283a810389c29de05bf',
    messagingSenderId: '388888154670',
    projectId: 'loginsignup-87c6b',
    authDomain: 'loginsignup-87c6b.firebaseapp.com',
    storageBucket: 'loginsignup-87c6b.appspot.com',
    measurementId: 'G-HNCK0C2742',
  );
}
